builds:
- binary: ppc
  main: ./cmd/ppc/main.go
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - amd64
  - 386
  - arm
- binary: pps
  main: ./cmd/pps/main.go
  goos:
  - windows
  - darwin
  - linux
  - freebsd
  goarch:
  - amd64
  - 386
  - arm

